StylesPath = styles

MinAlertLevel = suggestion

Packages = Microsoft, write-good, Joblint, alex, proselint, Readability, \
  https://github.com/ChrisChinchilla/Openly/releases/download/{LATEST_RELEASE}/Openly.zip, \
  https://github.com/tbhb/vale-ai-tells/releases/download/v1.21.0/ai-tells.zip, \
  https://github.com/tbhb/vale-ai-tells/releases/download/v1.21.0/ai-tells-commits.zip


[*.{md,rst}]
# ^ This section applies to only Markdown files.
#
# You can change (or add) file extensions here
# to apply these settings to other file types.
#
# For example, to apply these settings to both
# Markdown and reStructuredText:
#
# [*.{md,rst}]
BasedOnStyles = Vale, Microsoft, write-good, Joblint, alex, proselint, Readability, Openly, ai-tells

[formats]
COMMIT_EDITMSG = md

[{COMMIT_EDITMSG,.git/COMMIT_EDITMSG}]
BasedOnStyles = ai-tells, ai-tells-commits
