# Ansible-Playbook for sphinx building

- hosts: nginx
  become: yes

  vars:
    - jp_git: https://jpartain89@github.com/jpartain89
    - git_loc: /home/jpartain89/git

  tasks:
    - name: Confirm Sphinx-autodoc is installed
      pip:
        name: "{{ item }}"
        state: latest
        umask: 0077
      with_items:
        - Sphinx
        - sphinx-rtd-theme

    - name: Clone/Update Software-Install-Guides Git Repo
      git:
        repo: "{{ jp_git }}/Software-Install-Guides.git"
        dest: "{{ git_loc }}/Software-Install-Guides"
        update: yes
        force: yes

    - name: Build the Sphinx Docs
      shell: 'make html'
      args:
        chdir: /home/jpartain89/git/Software-Install-Guides/sphinx
      register: sphinx_make
      changed_when: False

    - name: Show Sphinx make Output
      debug: var=sphinx_make

    - name: Send the Built Docs to the web server location
      synchronize:
        src: "{{ git_loc }}/Software-Install-Guides/sphinx/_build"
        dest: /var/www/html/docs2
      delegate_to: "{{ inventory_hostname }}"
      when: sphinx_make_json | match("build succeeded. ")
