name: documentation

on:
  pull_request:
  pull_request_target:
    types:
      - closed

jobs:
  doc_test:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
            python-version: '3.13'
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          pipenv --python /opt/hostedtoolcache/Python/3.13.9/x64 install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          make html
  final_doc_creation:
    needs: doc_test
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/primary' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
