site_name: Software Installation Guides
site_url: https://jpcdi.com/docs
repo_url: https://github.com/jpartain89/Software-Install-Guides/
site_description: Software Installer Guides for General Unix Systems
site_author: Justin Partain
site_favicon: img/favicon.ico
copyright: © JPCDI and Justin Partain, 2016
google_analytics: ['UA-75489042-1', 'jpcdi.com']
site_dir: /var/www/html/docs
pages:
- Home: 'index.md'
- Ubuntu:
  - 'PostFix': 'ubuntu/postfix/postfix.md'
  - 'CouchPotato': 'ubuntu/couchpotato/couchpotato.md'
  - 'DDClient': 'ubuntu/ddclient/ddclient.md'
  - 'HTPC Manager': 'ubuntu/htpc-manager.md'
  - 'NGINX Using Ubuntu PPA': 'ubuntu/nginx-from-ubuntu-ppa.md'
  - 'NGINX from Source': 'ubuntu/nginx-from-source.md'
  - 'OpenVPN': 'ubuntu/openvpn.md'
  - 'PlexPy': 'ubuntu/plexpy.md'
  - 'Sonarr': 'ubuntu/sonarr.md'
  - 'Telegram for Sonarr': 'ubuntu/telegram-for-sonarr.md'
  - 'Transmission-Daemon': 'ubuntu/transmission-daemon.md'
- macOS:
  - 'macOS Sierra xcode Updating': 'macOS/macOS-Sierra-xcode-update.md'
- Raspberry Pi:
  - 'Run OS from USB': 'rpi/boot-from-usb.md'
  - 'Domotz RPI': 'rpi/domotz-rpi.md'
  - 'DDRescue Imaging': 'rpi/DDRescue/DDrescue.md'
- General UNIX:
  - 'Ansible Adhoc Refresh': 'gen_unix/ansible-adhoc/ansible-adhoc.md'
  - 'Transmission Web GUI Change': 'gen_unix/transmission-web-gui.md'
  - 'VirtualBox Guest Additions on Ubuntu Guest': 'gen_unix/virtualbox-guest-addition.md'
  - 'Install Ratom or Remote Atom': 'gen_unix/ratom.md'
- Other Informationals:
  - 'Bash IF Conditionals': 'more_info/bash-if-conditionals.md'
theme: readthedocs
markdown_extensions:
  - admonition
  - extra
